// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/auth": {
    params: {};
  };
  "/match-jd": {
    params: {};
  };
  "/analyze-cv": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/resume/:id": {
    params: {
      "id": string;
    };
  };
  "/jobs": {
    params: {};
  };
  "/wipe": {
    params: {};
  };
  "/admin/jobs": {
    params: {};
  };
  "/admin/make-admin": {
    params: {};
  };
  "/api/jobs": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/auth" | "/match-jd" | "/analyze-cv" | "/profile" | "/resume/:id" | "/jobs" | "/wipe" | "/admin/jobs" | "/admin/make-admin" | "/api/jobs";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
  "routes/match-jd.tsx": {
    id: "routes/match-jd";
    page: "/match-jd";
  };
  "routes/analyze-cv.tsx": {
    id: "routes/analyze-cv";
    page: "/analyze-cv";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/resume.tsx": {
    id: "routes/resume";
    page: "/resume/:id";
  };
  "routes/jobs.tsx": {
    id: "routes/jobs";
    page: "/jobs";
  };
  "routes/wipe.tsx": {
    id: "routes/wipe";
    page: "/wipe";
  };
  "routes/admin/jobs.tsx": {
    id: "routes/admin/jobs";
    page: "/admin/jobs";
  };
  "routes/admin/make-admin.tsx": {
    id: "routes/admin/make-admin";
    page: "/admin/make-admin";
  };
  "routes/api.jobs.tsx": {
    id: "routes/api.jobs";
    page: "/api/jobs";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
  "routes/match-jd": typeof import("./app/routes/match-jd.tsx");
  "routes/analyze-cv": typeof import("./app/routes/analyze-cv.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/resume": typeof import("./app/routes/resume.tsx");
  "routes/jobs": typeof import("./app/routes/jobs.tsx");
  "routes/wipe": typeof import("./app/routes/wipe.tsx");
  "routes/admin/jobs": typeof import("./app/routes/admin/jobs.tsx");
  "routes/admin/make-admin": typeof import("./app/routes/admin/make-admin.tsx");
  "routes/api.jobs": typeof import("./app/routes/api.jobs.tsx");
};